# Generated by Django 3.0.5 on 2020-04-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquityOSI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubiquityOSI.Area', verbose_name='<font size="3.5"><b>Select Nearest Areas Below:</b></font>'),
        ),
    ]
