# Generated by Django 3.0.4 on 2020-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquityOSI', '0002_remove_postservices_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postservices',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post-services'),
        ),
    ]
