# Generated by Django 3.0.14 on 2023-01-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubiquityOSI', '0002_auto_20200412_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservices',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubiquityOSI.Area', verbose_name='<font size="3.5"><b>Select Area Below:</b></font> <br> (Select Area Nearest to your Location [Select Carefully])'),
        ),
    ]
